LOSS_OF_CONTROL_STORAGE = LOSS_OF_CONTROL_STORAGE or {};

local List = LOSS_OF_CONTROL_STORAGE;
-- Spell        ID             Type      priority
List[12826] = { LOSS_OF_CONTROL_DISPLAY_POLYMORPH, 6 }; -- Sheep
List[51514] = { LOSS_OF_CONTROL_DISPLAY_POLYMORPH, 6 }; -- Hex
List[71103] = { LOSS_OF_CONTROL_DISPLAY_POLYMORPH, 6 }; -- Combobulating Spray
List[70410] = { LOSS_OF_CONTROL_DISPLAY_POLYMORPH, 6 }; -- Polymorph: Spider

List[14309] = { LOSS_OF_CONTROL_DISPLAY_FREEZE, 6 }; -- Freezing Trap Effect
List[43415] = { LOSS_OF_CONTROL_DISPLAY_FREEZE, 6 }; -- Freezing Trap
List[60210] = { LOSS_OF_CONTROL_DISPLAY_FREEZE, 6 }; -- Freezing Arrow
List[49203] = { LOSS_OF_CONTROL_DISPLAY_FREEZE, 6 }; -- Hungering Cold
List[66012] = { LOSS_OF_CONTROL_DISPLAY_FREEZE, 6 }; -- Freezing Slash
List[48400] = { LOSS_OF_CONTROL_DISPLAY_FREEZE, 6 }; -- Frost Tomb
List[67650] = { LOSS_OF_CONTROL_DISPLAY_FREEZE, 6 }; -- Arctic Breath

List[33786] = { LOSS_OF_CONTROL_DISPLAY_CYCLONE, 7 }; -- Cyclone

List[710]   = { LOSS_OF_CONTROL_DISPLAY_BANISH, 5 }; -- Banish
List[30940] = { LOSS_OF_CONTROL_DISPLAY_BANISH, 5 }; -- Burning Nova
List[70645] = { LOSS_OF_CONTROL_DISPLAY_BANISH, 5 }; -- Chains of Shadow

List[6358]  = { LOSS_OF_CONTROL_DISPLAY_CHARM, 6 }; -- Seducation

List[605]   = { LOSS_OF_CONTROL_DISPLAY_POSSESS, 6 }; -- Mind Control
List[71289] = { LOSS_OF_CONTROL_DISPLAY_POSSESS, 6 }; -- Dominate Mind
List[51503] = { LOSS_OF_CONTROL_DISPLAY_POSSESS, 6 }; -- Domination
List[70923] = { LOSS_OF_CONTROL_DISPLAY_POSSESS, 6 }; -- Uncontrollable Frenzy
List[13181] = { LOSS_OF_CONTROL_DISPLAY_POSSESS, 6 }; -- Gnomish Mind Control Cap

List[19503] = { LOSS_OF_CONTROL_DISPLAY_CONFUSE, 6 }; -- Scatter Shot
List[70302] = { LOSS_OF_CONTROL_DISPLAY_CONFUSE, 6 }; -- Blinding Dirt
List[74456]               = { LOSS_OF_CONTROL_DISPLAY_CONFUSE, 6 }; -- Conflagration

List[20066] = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Repentance
List[1776]  = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Gouge
List[32905] = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Glare
List[29676] = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Rolling Pin
List[70432] = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Blood Sap
List[67769] = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Cobalt Frag Bomb
List[19784] = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Dark Iron Bomb
List[4064]  = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Rough Copper Bomb
List[4065]  = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Large Copper Bomb
List[4066]  = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Small Bronze Bomb
List[4067]  = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Big Bronze Bomb
List[4068]  = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Iron Grenade
List[4069]  = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Big Iron Bomb
List[12024] = { LOSS_OF_CONTROL_DISPLAY_INCAPACITATE, 5 }; -- Net

List[51724] = { LOSS_OF_CONTROL_DISPLAY_SAP, 6 }; -- Sap

List[10955] = { LOSS_OF_CONTROL_DISPLAY_SHACKLE_UNDEAD, 6 }; -- Shackle Undead

List[49012] = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Wyvern Sting
List[18658] = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Hibernate
List[59165] = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Sleep
List[36333] = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Anesthetic
List[3636]  = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Crystalline Slumber
List[16798] = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Enchanting Lullaby
List[7967]  = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Naralex's Nightmare
List[29679] = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Bad Poetry
List[8040]  = { LOSS_OF_CONTROL_DISPLAY_SLEEP, 6 }; -- Druid's Slumber

List[64044]               = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Psychic Horror
List[74384]               = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Intimidating Roar
List[16508]               = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Intimidating Roar
List[48696]               = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Intimidating Roar
List[51467]               = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Intimidating Roar
List[49106] = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Terrify
List[53438] = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Incite Horror
List[47860] = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Death Coil
List[67677] = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Waking Nightmare
List[73070] = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Incite Terror
List[48144] = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Terrifying Roar
List[72435] = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Defiling Horror
List[36922] = { LOSS_OF_CONTROL_DISPLAY_HORROR, 3 }; -- Bellowing Roar

List[42380]               = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Conflagration
List[42950] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Dragons Breath
List[2094]  = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Blind
List[26108] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Glimpse of Madness
List[52524] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Blinding Webs
List[48558] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Backfire
List[66862] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Radiance
List[42805] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Dirty Trick
List[36834] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Arcane Disruption
List[17928] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Howl of Terror
List[30057] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Improved Howl of Terror
List[69240] = { LOSS_OF_CONTROL_DISPLAY_DISORIENT, 6 }; -- Vile Gas

List[53588] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Nether Shock
List[1330]  = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Garrote
List[25046] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Arcane Torrent
List[15487] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Silence
List[34490] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Silencing Shot
List[18425] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Improved Kick
List[18469] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Improved Counterspell
List[19647] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Spell Lock
List[63529] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Shield of the Templar
List[49916] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Strangulate
List[18498] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Gag Order
List[19821] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Arcane Bomb
List[55663] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Deafening Roar
List[6726]  = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Silence
List[58526] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Azure Bindings
List[34190] = { LOSS_OF_CONTROL_DISPLAY_SILENCE, 1 }; -- Arcane Orb

List[53543] = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Snatch
List[51722] = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Dismantle
List[676]   = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Disarm
List[53359] = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Chimera Shot
List[64058] = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Psychic Horror
List[64346] = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Fiery Payback
List[14180] = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Sticky Tar
List[33126] = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Dropped Weapon
List[36208] = { LOSS_OF_CONTROL_DISPLAY_DISARM, 2 }; -- Steal Weapon

List[20511] = { LOSS_OF_CONTROL_DISPLAY_FEAR, 3 }; -- Intimidating Shout
List[6215]  = { LOSS_OF_CONTROL_DISPLAY_FEAR, 3 }; -- Fear
List[10890] = { LOSS_OF_CONTROL_DISPLAY_FEAR, 3 }; -- Psychic Scream
List[14327] = { LOSS_OF_CONTROL_DISPLAY_FEAR, 3 }; -- Scare Beast
List[10326] = { LOSS_OF_CONTROL_DISPLAY_FEAR, 3 }; -- Turn Evil
List[5246]  = { LOSS_OF_CONTROL_DISPLAY_FEAR, 3 }; -- Intimidating Shout
List[29544] = { LOSS_OF_CONTROL_DISPLAY_FEAR, 3 }; -- Frightening Shout

List[15655]               = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Shield Slam
List[8285]                = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Rampage
List[68771]               = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Thundering Stomp
List[49802] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Maim
List[5918]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Shadowstalker Stab
List[15283] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Stunning Blow
List[36877] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Stun Forever
List[16075] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Throw Axe
List[16045] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Encage
List[47772] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Ice Nova
List[69222] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Throw Shield
List[48131] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Stomp
List[50234] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Crush
List[55959] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Embrace of the Vampyr
List[47995] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Intercept (Pet)
List[53562] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Ravage
List[53568] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Sonic Blast
List[12809] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Concussion Blow
List[46968] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Shockwave
List[10308] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Hammer of Justice
List[8983]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Bash
List[19577] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Intimidation
List[8643]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Kidney Shot
List[20549] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- War Stomp
List[20252] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Intercept
List[44572] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Deep Freeze
List[30414] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Shadowfury
List[2812]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Holy Wrath
List[22703] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Inferno Effect
List[60995] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Demon Charge
List[47481] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Gnaw  
List[12355] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Impact
List[16544] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Improved Fire Nova Totem
List[39796] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Stoneclaw Totem
List[20170] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Seal of Justice
List[12798] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Revenge Stunned 
List[1833]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Cheap Shot
List[49803] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Pounce 
List[7922]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Charge Stun
List[66683] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Massive Crash
List[66770] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Ferocious Butt
List[70980] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Web Wrap
List[66547] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Confess
List[51750] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Screams of the Dead
List[53148] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Charge
List[35570] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Charge
List[52825] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Swoop
List[35011] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Knockdown
List[58154] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Hammer of Injustice    
List[51491] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Unrelenting Strike
List[21749] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Thorn Volley
List[3635]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Crystal Gaze
List[35313] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Hypnotic Gaze
List[6524]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Ground Tremor
List[6607]  = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Lash
List[47700] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Crystal Freeze
List[43936] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Knockdown Spin
List[52696] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Constricting Chains
List[58848] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Time Stop
List[72428] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Despair Stricken
List[69133] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Lethargy
List[29484] = { LOSS_OF_CONTROL_DISPLAY_STUN, 5 }; -- Web Spray

List[52086]               = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Web Wrap
List[53548] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Pin
List[47698] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Crystal Chains
List[48179] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Crystallize
List[50690] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Immobilizing Field
List[49711] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Hooked Net
List[53322] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Crushing Webs
List[42917] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Frost Nova
List[53308] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Entangling Roots
List[53313] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Natures Grasp
List[8377]  = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Earthgrab   
List[19675] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Feral Charge Effect
List[19306] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Counterattack
List[19185] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Entrapment
List[54706] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Venom Web Spray
List[4167]  = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Web
List[33395] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Freeze
List[12494] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Frostbite
List[55080] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Shattered Barrier
List[58373] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 5 }; -- Glyph of Hamstring
List[23694] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 5 }; -- Improved Hamstring
List[39965] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Frost Grenade
List[55536] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Frostweave Net
List[13099] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Net-o-MaticК
List[52491] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Web Explosion
List[56632] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Tangled Webs
List[49704] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Encasing Webs
List[61579] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Runic Focus
List[71647] = { LOSS_OF_CONTROL_DISPLAY_ROOT, 4 }; -- Ice Trap
